import React, { useState, useRef, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ShieldAlert, ArrowRight, Loader2, KeyRound, AlertCircle } from 'lucide-react';
import { useAuthStore } from '../../stores/authStore';
import { logAdminAudit } from '../../lib/audit';
import { toast } from 'sonner';

export const AdminMfaVerifyPage: React.FC = () => {
  const navigate = useNavigate();
  const { user, setMfaVerified } = useAuthStore();

  const [digits, setDigits] = useState<string[]>(['', '', '', '', '', '']);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [useBackupCode, setUseBackupCode] = useState(false);
  const [backupCodeInput, setBackupCodeInput] = useState('');

  const inputRefs = useRef<(HTMLInputElement | null)[]>([]);

  useEffect(() => {
    if (!useBackupCode) {
      inputRefs.current[0]?.focus();
    }
  }, [useBackupCode]);

  const handleDigitChange = (index: number, val: string) => {
    setError(null);
    const cleaned = val.replace(/\D/g, '');

    if (cleaned.length > 1) {
      // Handle paste of whole code
      const chars = cleaned.slice(0, 6).split('');
      const newDigits = [...digits];
      chars.forEach((c, idx) => {
        if (index + idx < 6) newDigits[index + idx] = c;
      });
      setDigits(newDigits);
      const nextIndex = Math.min(index + chars.length, 5);
      inputRefs.current[nextIndex]?.focus();
      if (newDigits.every((d) => d !== '')) {
        submitMfa(newDigits.join(''));
      }
      return;
    }

    const newDigits = [...digits];
    newDigits[index] = cleaned;
    setDigits(newDigits);

    if (cleaned && index < 5) {
      inputRefs.current[index + 1]?.focus();
    }

    // Auto submit if all 6 filled
    if (newDigits.every((d) => d !== '')) {
      submitMfa(newDigits.join(''));
    }
  };

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Backspace' && !digits[index] && index > 0) {
      inputRefs.current[index - 1]?.focus();
    }
  };

  const submitMfa = async (code: string) => {
    setLoading(true);
    setError(null);

    try {
      // Simulate verification check
      await new Promise((resolve) => setTimeout(resolve, 500));

      setMfaVerified(true);
      await logAdminAudit({
        action: 'MFA_CHALLENGE_SUCCESS',
        entity_type: 'admin_session',
        entity_id: user?.id || 'usr-admin-01',
        details: {
          verification_method: useBackupCode ? 'backup_code' : 'totp_token',
        },
      });

      toast.success('Two-Factor Authentication verified. Access granted.');
      navigate('/admin');
    } catch (err: any) {
      setError('Invalid authentication code. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleBackupSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!backupCodeInput.trim()) {
      setError('Please enter your emergency backup code.');
      return;
    }
    submitMfa(backupCodeInput.trim());
  };

  return (
    <div className="min-h-screen bg-[#0B0F17] flex flex-col justify-center py-12 sm:px-6 lg:px-8 text-slate-100 selection:bg-amber-500 selection:text-slate-950">
      <div className="sm:mx-auto sm:w-full sm:max-w-md text-center">
        <div className="inline-flex items-center justify-center w-14 h-14 rounded-xl bg-amber-500 text-slate-950 mb-4 shadow-lg shadow-amber-500/20">
          <KeyRound className="w-7 h-7" />
        </div>
        <h2 className="text-2xl font-bold tracking-tight text-white">
          Two-Step Verification
        </h2>
        <p className="mt-1 text-xs text-slate-400">
          Enter the 6-digit verification code generated by your authenticator app for{' '}
          <span className="text-amber-400 font-semibold">{user?.email || 'admin@intonepal.com'}</span>.
        </p>
      </div>

      <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
        <div className="bg-[#111827] py-8 px-6 shadow-2xl rounded-xl border border-[#1F2937] sm:px-10">
          {error && (
            <div className="mb-5 p-3 rounded-lg bg-red-950/50 border border-red-800 text-red-300 text-xs flex items-center gap-2">
              <AlertCircle className="w-4 h-4 text-red-400 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          {!useBackupCode ? (
            <div className="space-y-6">
              {/* 6-DIGIT BOXES */}
              <div className="flex justify-between gap-2 sm:gap-3">
                {digits.map((digit, index) => (
                  <input
                    key={index}
                    ref={(el) => {
                      inputRefs.current[index] = el;
                    }}
                    type="text"
                    inputMode="numeric"
                    maxLength={1}
                    value={digit}
                    onChange={(e) => handleDigitChange(index, e.target.value)}
                    onKeyDown={(e) => handleKeyDown(index, e)}
                    className="w-11 h-13 sm:w-12 sm:h-14 text-center text-xl font-bold font-mono bg-[#070A10] border border-slate-700 rounded-lg text-amber-400 focus:outline-none focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-all"
                  />
                ))}
              </div>

              <button
                type="button"
                disabled={loading || digits.some((d) => d === '')}
                onClick={() => submitMfa(digits.join(''))}
                className="w-full flex justify-center items-center gap-2 py-2.5 px-4 rounded-lg shadow-sm text-xs font-bold uppercase tracking-wider text-slate-950 bg-amber-500 hover:bg-amber-400 disabled:opacity-50 transition-colors"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Validating Security Token...
                  </>
                ) : (
                  <>
                    Verify & Enter Console
                    <ArrowRight className="w-4 h-4" />
                  </>
                )}
              </button>

              <div className="pt-2 text-center">
                <button
                  type="button"
                  onClick={() => setUseBackupCode(true)}
                  className="text-xs text-amber-400 hover:text-amber-300 hover:underline transition-colors"
                >
                  Lost access to phone? Use an emergency backup code
                </button>
              </div>
            </div>
          ) : (
            <form onSubmit={handleBackupSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                  Emergency 8-Character Backup Code
                </label>
                <input
                  type="text"
                  required
                  placeholder="e.g. A9F2-K84D"
                  value={backupCodeInput}
                  onChange={(e) => setBackupCodeInput(e.target.value.toUpperCase())}
                  className="w-full px-3 py-2 bg-[#070A10] border border-slate-700 rounded-lg font-mono text-sm text-amber-400 placeholder-slate-600 focus:outline-none focus:ring-2 focus:ring-amber-500"
                />
              </div>

              <button
                type="submit"
                disabled={loading || !backupCodeInput.trim()}
                className="w-full flex justify-center items-center gap-2 py-2.5 px-4 rounded-lg shadow-sm text-xs font-bold uppercase tracking-wider text-slate-950 bg-amber-500 hover:bg-amber-400 disabled:opacity-50 transition-colors"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Verifying Backup Code...
                  </>
                ) : (
                  <>
                    Authenticate with Backup Code
                    <ArrowRight className="w-4 h-4" />
                  </>
                )}
              </button>

              <div className="text-center pt-2">
                <button
                  type="button"
                  onClick={() => setUseBackupCode(false)}
                  className="text-xs text-slate-400 hover:text-white transition-colors"
                >
                  ← Back to authenticator 6-digit code
                </button>
              </div>
            </form>
          )}

          <div className="mt-6 pt-4 border-t border-[#1F2937] flex items-center justify-between text-[11px] text-slate-400">
            <Link to="/admin/mfa-setup" className="hover:text-amber-400">
              Configure New Device
            </Link>
            <Link to="/admin/login" className="hover:text-slate-200">
              Cancel & Log Out
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};
